### ISSUE TITLE
How can I customize the color?

### ISSUE THREAD

**Issue by CatsMiaow** [robertrossmann/vscode-remedy#13]
In my eyes, the color of the const and readonly variables is gray series, so it's not clear, which reduces readability.
![image](https://user-images.githubusercontent.com/1300172/83393368-a366d680-a431-11ea-85c8-5b19413b5057.png)

How can I change the color of the const variable and readonly variable to previous color(white?)?

**Comment by robertrossmann** [comment]
Hi @CatsMiaow, thanks for the feedback! I am still considering this particular aspect. Not sure, either, if I like it or what. I would like to somehow adjust the colours of readonly variables and properties, I am just not sure if this is the right approach. If you have any suggestions in this area please let me know!

To have the readonly variables and properties regular white again, you may put the following into your VS Code's settings:

```json

"editor.semanticTokenColorCustomizations": {
  "[Remedy - Dark (Tilted)]": {
    "rules": {
      "variable.readonly": "#F9E7C4",
      "property.readonly": "#F9E7C4"
    }
  }
}

```
