### ISSUE TITLE
IntelliJ/Webstorm/AndroidStudio theme

### ISSUE THREAD

**Issue by josephmbeveridge** [robertrossmann/vscode-remedy#21]
Loving this theme and was wondering if you would be willing to port it to the IntelliJ set of IDEs.

**Comment by robertrossmann** [comment]
Hi @josephmbeveridge , thanks for the kind words! ❤️ Unfortunately I do not use any of the IntelliJ products so I am not personally interested in porting it to that IDE, however I encourage you to create your own version with the colours defined in this theme. If you do create a port yourself please kindly refer to this original theme as a source of inspiration. 🙏

Good luck! 💪
