### ISSUE TITLE
React components tags have the same color as HTML tags

### ISSUE THREAD

**Issue by Bosphoramus** [robertrossmann/vscode-remedy#22]
![image](https://user-images.githubusercontent.com/45177590/104815639-19c81580-5816-11eb-9c59-835dce986779.png)
![image](https://user-images.githubusercontent.com/45177590/104815671-35cbb700-5816-11eb-9211-2aba35228dda.png)

As you can see the HTML <audio> tag is the same color as the React <Library> components tag.
Dunno if this can be helpful: https://github.com/microsoft/TypeScript-TmLanguage/issues/415
I think thats the code that changes the tags color when it detecs the first letter is capitalized.

**Comment by robertrossmann** [comment]
Thanks for the report, I totally missed JSX/TSX scopes in the theme definition, it would seem! Now all React files (.jsx/.tsx) should look much better and have consistent colouring across all other types of code. 🎨 

I have also updated the colours of built-in HTML tags to those of other language built-ins (kind of a dark yellowish/orangeish?) while keeping React components regular yellow (just like classes). Hope this helps! ❤️

**Comment by Bosphoramus** [comment]
Helps a lot :)
I love the theme, the best i've tried, and i've tried a lot, thanks :D
