### ISSUE TITLE
Support for Svelte files

### ISSUE THREAD

**Issue by vabatta** [robertrossmann/vscode-remedy#26]
Hi,

can you add support for Svelte files syntax (`.svelte`)?

**Comment by robertrossmann** [comment]
Hi, I can definitely take a look! However, I would need a bit of help with that!

First of all, can you please share code snippet of a really complex Svelte source code, ideally something that demonstrates as much Svelte syntax as possible. And second, what VS Code extension do you use for Svelte syntax highlighting?

**Comment by vabatta** [comment]
For many examples of components and its syntax, you can have a look at [notus library](https://github.com/creativetimofficial/notus-svelte/tree/main/src/components).
It is similar to `vue` syntax with some added features (for example [reactive declarations](https://svelte.dev/tutorial/reactive-declarations)).

And here's the plugins:

Name: Svelte for VS Code
Id: svelte.svelte-vscode
Description: Svelte language support for VS Code
Version: 105.0.0
Publisher: Svelte
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

Name: Svelte Intellisense
Id: ardenivanov.svelte-intellisense
Description: Provides intellisense for data, events, slots etc. in components.
Version: 0.7.1
Publisher: ardenivanov
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ardenivanov.svelte-intellisense

**Comment by robertrossmann** [comment]
Thanks, I'll take a look! 👀

**Comment by robertrossmann** [comment]
Looking at `notus library` source code with the Svelte extension installed it all looks rather okay and as-expected - a mix of JS and HTML, all properly coloured. ✅ 🤷‍♂️ Are you seeing incorrect colouring somewhere?

**Comment by vabatta** [comment]
Yes, for example the coloring for the following is slightly different from what I would expect:
```html
<h1 class="bg-black">Welcome to SvelteKit</h1>
```

The `class` attribute don't get any coloring while in other languages (e.g. `react`) has its own color.

**Comment by robertrossmann** [comment]
Ooooh yeaaah... mmkay. 🤔

**Comment by robertrossmann** [comment]
Alrighty, Svelte support coming in hot!

It takes a few minutes for the extension update to appear in VS Code so give it a while and test it out. If you find any additional discrepancies between a regular HTML and Svelte, or regular JS and svelte `<script>` block, let me know and I'll see if I can fix it. 💪 Enjoy! 🍻
