### ISSUE TITLE
Please add support for VSCodium

### ISSUE THREAD

**Issue by mansoor-s** [robertrossmann/vscode-remedy#27]
Thanks for making my favorite theme!

Would you please consider publishing this theme for [VSCodium](https://vscodium.com/) on [Open VSX](https://open-vsx.org/)? VSCodium is the opensource release of VS Code minus the tracking & telemetry.

Instructions on how to publish are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thank you

**Comment by robertrossmann** [comment]
Hi! Thanks for the suggestion! At this moment I am only focusing on VS Code and don't plan on extending support to VS Codium.

**Comment by robertrossmann** [comment]
@mansoor-s not sure if it's possible but I also publish the theme package (`.vsix`) to [GitHub Releases](https://github.com/robertrossmann/vscode-remedy/releases/tag/5.20.0). While you are not going to have automatic updates, I think you could at least install the theme and check back here once in a while to download newer versions. 🤔 

![Screenshot 2024-02-07 at 11 53 35](https://github.com/robertrossmann/vscode-remedy/assets/3058150/9c5f3c52-5daa-42f6-9ebe-d4a6fd8e00d7)
