### ISSUE TITLE
Lighter brown instead of gray color shown in preview?

### ISSUE THREAD

**Issue by relgies** [robertrossmann/vscode-remedy#37]
Below is what the installation looks like on my Windows PC.  I took a screen shot of it with the Marketplace open where you can see the contrast of how it's shown in your preview image.  I'm just curious why yours is a much darker gray color than mine which is much more brown.

Thanks for any information.

![image](https://github.com/robertrossmann/vscode-remedy/assets/37893046/2ab1868f-8fba-4311-8f60-cb09572ca180)

**Comment by robertrossmann** [comment]
Hey @relgies , the screenshot in the repository was quite outdated, unfortunately. Sorry if that misled you into installing the theme and then disappointing you.

The way it looks on your machine is correct. I updated the screenshots to match current state of the theme and released a new version to Marketplace to make sure people are not getting confused.

I hope you still like it the way it is right now! ❤️ 🤞

**Comment by relgies** [comment]
No disappointment at all, you honestly have the best theme out there and it needs far more publicity than it gets!  I will say though I do like the more grey color than the brown, so if you ever came out with a "Light, Dark, and Darker" set of themes with the old more neutral grey color then it would be absolutely perfect.  Either way, even though I don't prefer the brown as much as the grey it's still an absolutely amazing theme!

Thank you again for all the hard work on it!
