### ISSUE TITLE
Terminal text unreadable on mouseover when terminal sticky scroll is on

### ISSUE THREAD

**Issue by mitsukuri** [robertrossmann/vscode-remedy#40]
First of all, Robert, I'd like to thank you for this wonderful tasteful theme, it is just perfect. Whenever I think I got tired and go trying other themes, I would return to Remedy in just a few minutes :)

Now to the issue:
When the sticky scroll is enabled for terminal (`terminal.integrated.stickyScroll.enabled: true`, introduced in VS Code `1.85`) and the command in the sticky header is getting a mouseover event, it becomes unreadable. Which does not occur with other themes.

Here's Remedy:
https://github.com/user-attachments/assets/b0ba2751-b396-457a-9030-e70c7fdc0773

And here's default Light
https://github.com/user-attachments/assets/824347d4-26f3-4a3a-b922-f71dbb52fb96

VS Code `1.93.1`
Remedy `5.25.0`

**Comment by robertrossmann** [comment]
Ugh, that looks awful, I'll take a look. And thanks for the kind words, happy that you like it! ❤️

**Comment by mitsukuri** [comment]
Thank you so much fox the fix!
