### ISSUE TITLE
The tilted variants have been removed?

### ISSUE THREAD

**Issue by CatsMiaow** [robertrossmann/vscode-remedy#7]
![image](https://user-images.githubusercontent.com/1300172/74403906-40ded000-4e6c-11ea-8460-7d6bcef434c4.png)

I was using `Remedy - Straight Up` but it was tilted after v4.0.0

https://github.com/robertrossmann/vscode-remedy/blob/master/packages/generators/mktokens/tokens/tilted/index.mjs
`Italic` remains in the source code.

Do I understand that 'Remedy-Straight Up' has been removed?

**Comment by robertrossmann** [comment]
Hi @CatsMiaow, yes, the straight-up variant [has been removed in v4](https://github.com/robertrossmann/vscode-remedy/blob/master/CHANGELOG.md#400-2020-02-12) as I was quite overwhelmed with the complexities of reworking the theme to support both dark and light variants without too much duplication and keeping the straight variant in the game was quite above my mental bar to handle comfortably.

However now that it's all settled I took a second look at the current state of affairs and it was super easy to re-introduce the straight variant. 🎉 Look out for _v4.1_ release soon!
