### ISSUE TITLE
The property is displayed as a string color.

### ISSUE THREAD

**Issue by CatsMiaow** [robertrossmann/vscode-remedy#8]
`Remedy - Dark`
![image](https://user-images.githubusercontent.com/1300172/75742492-1daf8e00-5d51-11ea-8b9d-ca7ce41cbe4d.png)

`One Dark Pro`
![image](https://user-images.githubusercontent.com/1300172/75742515-3455e500-5d51-11ea-8276-5daca3ffdb0f.png)

When using template literals, the colors of `id` and `content` are different and are the same as the string colors. Is it intended?

**Comment by robertrossmann** [comment]
Thanks for the report! I have not noticed this myself yet, I’ll check this as soon as I get to a computer.

Are you perchance using the new experimental _semantic highlighting_ functionality (`editor.semanticHighlighting.enable` needs to be turned on, I believe) ? It messes up the colour scheme real bad at this time... 🤷‍♂️

**Comment by robertrossmann** [comment]
Unfortunately I cannot reproduce this on my side. Could you please place your cursor onto the `id` (ideally between the _i_ and _d_), open up the token inspector hover (`Developer: Inspect Editor Tokens and Scopes` in the command palette) and send me a screenshot of that? 🙏 It looks like this:

<img width="798" alt="Inspect editor tokens and scopes" src="https://user-images.githubusercontent.com/3058150/75778329-dd074300-5d57-11ea-939b-708e6136063f.png">

**Comment by CatsMiaow** [comment]
`"editor.semanticHighlighting.enabled": false`
![image](https://user-images.githubusercontent.com/1300172/75779023-3db86f00-5d9c-11ea-8ab1-28b9d92ba2b5.png)

`"editor.semanticHighlighting.enabled": true`
![image](https://user-images.githubusercontent.com/1300172/75779113-66d8ff80-5d9c-11ea-9a86-2fca7f909e6d.png)

semanticHighlighting is the default value(`false`).
![image](https://user-images.githubusercontent.com/1300172/75779562-32197800-5d9d-11ea-9b4c-654a5810e051.png)

VS Code
![image](https://user-images.githubusercontent.com/1300172/75779758-8f152e00-5d9d-11ea-8339-1caa0475d83c.png)

**Comment by CatsMiaow** [comment]
Found the cause. This is a problem with other extensions.
https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar
https://github.com/Microsoft/TypeScript-TmLanguage

Disable the extension solved the problem. Thank you.

**Comment by robertrossmann** [comment]
Ah okay, good! I was a little curious as to why that `.id` property was being classified as something `DOM`-related... 🤷‍♂  Thanks for reporting the issue, though!
